# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a01f985202faf19e077ccf896f6630b14dfcc36593eeb53acb313ca470029f9423dbd2279aebc30e889be168cd194c3ae532112172e1c258374c82a91a21a43a
  #  we have added in the strip keys here
  stripe_key: pk_test_UeYYhLoEN2gZAAcAZnLpyeZA
  stripe_secret: sk_test_QN85rb0sbKiwMVGXLlF1hxMp

test:
  secret_key_base: ee4ac691eee5c426e282e46a554aeb72d84c8898a6768df21c75f6bbcd0404bdff6ace95e446a710d0778e3ff0676ac47adf8c6ceeac4ef7726deb65e8a235b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # ADDING STRIPE PRODUCTION KEYS
  stripe_key: pk_live_x9NaCCgz6UkZ54n26l0Kg85I
  stripe_secret: sk_live_RgRtOJWcUU7iHRtKl9UM3oHv





